import { addDays, format, startOfWeek } from "date-fns";
import type { Client, Task } from "./types";

export const CLIENTS: Client[] = [
  { id: "anoreg", name: "ANOREG/TO", color: "#7657ff", initials: "AN" },
  { id: "krd", name: "KRD Equipamentos", color: "#2479db", initials: "KR" },
  { id: "weeki", name: "Weeki", color: "#d8438e", initials: "WK" },
];

const isoDate = (date: Date) => format(date, "yyyy-MM-dd");

export function createSeedTasks(referenceDate = new Date()): Task[] {
  const monday = startOfWeek(referenceDate, { weekStartsOn: 1 });
  const now = new Date().toISOString();
  const base = {
    attachments: [],
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  };

  return [
    {
      ...base,
      id: "seed-1",
      title: "Finalizar identidade da campanha",
      description: "Ajustar as últimas peças e preparar os arquivos finais para aprovação.",
      clientId: "anoreg",
      status: "in_progress",
      priority: "high",
      scheduledDate: isoDate(addDays(monday, 0)),
      scheduledTime: "09:30",
      dueDate: isoDate(addDays(monday, 0)),
      dueTime: "17:00",
      estimateMinutes: 120,
      tags: ["Design"],
      checklist: [
        { id: "check-1", label: "Revisar textos", completed: true },
        { id: "check-2", label: "Exportar peças", completed: false },
        { id: "check-3", label: "Enviar ao cliente", completed: false },
      ],
      notes: "Usar a versão aprovada da paleta institucional.",
      recurrence: { type: "none", days: [], endDate: "" },
      activity: [{ id: "act-1", text: "Demanda criada", createdAt: now }],
    },
    {
      ...base,
      id: "seed-2",
      title: "Atualizar página de produtos",
      description: "Publicar as novas especificações e substituir as imagens da RD60.",
      clientId: "krd",
      status: "review",
      priority: "medium",
      scheduledDate: isoDate(addDays(monday, 1)),
      scheduledTime: "14:00",
      dueDate: isoDate(addDays(monday, 2)),
      dueTime: "12:00",
      estimateMinutes: 90,
      tags: ["Site"],
      checklist: [
        { id: "check-4", label: "Atualizar informações técnicas", completed: true },
        { id: "check-5", label: "Revisar versão mobile", completed: true },
      ],
      notes: "",
      recurrence: { type: "none", days: [], endDate: "" },
      activity: [{ id: "act-2", text: "Movida para revisão", createdAt: now }],
    },
    {
      ...base,
      id: "seed-3",
      title: "Planejar conteúdos da semana",
      description: "Organizar temas, formatos e datas do calendário editorial.",
      clientId: "anoreg",
      status: "completed",
      priority: "medium",
      scheduledDate: isoDate(addDays(monday, 2)),
      scheduledTime: "10:00",
      dueDate: isoDate(addDays(monday, 2)),
      dueTime: "18:00",
      estimateMinutes: 60,
      tags: ["Social Media"],
      checklist: [],
      notes: "",
      recurrence: { type: "weekly", days: [], endDate: "" },
      activity: [{ id: "act-3", text: "Demanda concluída", createdAt: now }],
    },
    {
      ...base,
      id: "seed-4",
      title: "Revisar fluxo de criação de demandas",
      description: "Testar o formulário rápido e listar melhorias para a próxima versão.",
      clientId: "weeki",
      status: "not_started",
      priority: "high",
      scheduledDate: isoDate(addDays(monday, 3)),
      scheduledTime: "15:00",
      dueDate: isoDate(addDays(monday, 4)),
      dueTime: "17:00",
      estimateMinutes: 45,
      tags: ["Produto"],
      checklist: [
        { id: "check-6", label: "Criar demanda pelo botão global", completed: false },
        { id: "check-7", label: "Testar arrastar entre dias", completed: false },
      ],
      notes: "",
      recurrence: { type: "none", days: [], endDate: "" },
      activity: [{ id: "act-4", text: "Demanda criada", createdAt: now }],
    },
    {
      ...base,
      id: "seed-5",
      title: "Enviar relatório de desempenho",
      description: "Consolidar os principais números e enviar o resumo semanal.",
      clientId: "krd",
      status: "waiting",
      priority: "urgent",
      scheduledDate: isoDate(addDays(monday, 4)),
      scheduledTime: "11:30",
      dueDate: isoDate(addDays(monday, 4)),
      dueTime: "16:00",
      estimateMinutes: 60,
      tags: ["Administrativo"],
      checklist: [],
      notes: "Aguardando confirmação dos dados de vendas.",
      recurrence: { type: "none", days: [], endDate: "" },
      activity: [{ id: "act-5", text: "Status alterado para aguardando cliente", createdAt: now }],
    },
    {
      ...base,
      id: "seed-inbox",
      title: "Atualizar banner do site",
      description: "",
      clientId: "krd",
      status: "not_started",
      priority: "low",
      scheduledDate: null,
      scheduledTime: "",
      dueDate: "",
      dueTime: "",
      estimateMinutes: null,
      tags: [],
      checklist: [],
      notes: "",
      recurrence: { type: "none", days: [], endDate: "" },
      activity: [{ id: "act-6", text: "Capturada na Caixa de Entrada", createdAt: now }],
    },
  ] as Task[];
}
