import { addDays, format } from "date-fns";
import type { Appointment, EventType } from "./types";

const dateKey = (date: Date) => format(date, "yyyy-MM-dd");

export function createSeedEventTypes(): EventType[] {
  const now = new Date().toISOString();
  return [
    {
      id: "event-diagnostic",
      name: "Reunião de Diagnóstico",
      description: "Avaliação inicial de necessidades e definição dos próximos passos.",
      durationMinutes: 30,
      mode: "google_meet",
      price: null,
      includedInPlan: false,
      clientOnly: false,
      active: true,
      slug: "diagnostico",
      color: "#10b981",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "event-consulting",
      name: "Sessão de Consultoria",
      description: "Encontro aprofundado para análise, orientação e tomada de decisão.",
      durationMinutes: 60,
      mode: "video",
      price: 350,
      includedInPlan: false,
      clientOnly: false,
      active: true,
      slug: "consultoria",
      color: "#4f46e5",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "event-alignment",
      name: "Alinhamento Semanal",
      description: "Check-in rápido para revisar entregas, prioridades e pendências.",
      durationMinutes: 15,
      mode: "google_meet",
      price: null,
      includedInPlan: true,
      clientOnly: true,
      active: true,
      slug: "alinhamento",
      color: "#2563eb",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "event-workshop",
      name: "Workshop de Estratégia",
      description: "Imersão para planejamento, organização de metas e próximos ciclos.",
      durationMinutes: 120,
      mode: "google_meet",
      price: 800,
      includedInPlan: false,
      clientOnly: false,
      active: false,
      slug: "workshop",
      color: "#64748b",
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function createSeedAppointments(referenceDate = new Date()): Appointment[] {
  const now = new Date().toISOString();
  return [
    {
      id: "appointment-1",
      title: "Reunião de Diagnóstico",
      typeId: "event-diagnostic",
      clientId: "clinic-lumi",
      guestName: "",
      guestEmail: "",
      guestPhone: "",
      date: dateKey(referenceDate),
      time: "10:00",
      status: "confirmed",
      mode: "google_meet",
      location: "",
      meetingUrl: "",
      notes: "",
      source: "Agenda Weeki",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "appointment-2",
      title: "Sessão de Consultoria",
      typeId: "event-consulting",
      clientId: "krd",
      guestName: "",
      guestEmail: "",
      guestPhone: "",
      date: dateKey(referenceDate),
      time: "14:00",
      status: "confirmed",
      mode: "video",
      location: "",
      meetingUrl: "",
      notes: "",
      source: "Cadastro interno",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "appointment-3",
      title: "Alinhamento Semanal",
      typeId: "event-alignment",
      clientId: "anoreg",
      guestName: "",
      guestEmail: "",
      guestPhone: "",
      date: dateKey(addDays(referenceDate, 1)),
      time: "09:30",
      status: "confirmed",
      mode: "google_meet",
      location: "",
      meetingUrl: "",
      notes: "",
      source: "Agenda Weeki",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "appointment-4",
      title: "Sessão de Consultoria",
      typeId: "event-consulting",
      clientId: "casa-verde",
      guestName: "",
      guestEmail: "",
      guestPhone: "",
      date: dateKey(addDays(referenceDate, 2)),
      time: "15:00",
      status: "pending",
      mode: "google_meet",
      location: "",
      meetingUrl: "",
      notes: "Solicitação recebida pela página pública.",
      source: "Página pública",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "appointment-5",
      title: "Reunião de Diagnóstico",
      typeId: "event-diagnostic",
      clientId: null,
      guestName: "Novo contato",
      guestEmail: "",
      guestPhone: "",
      date: dateKey(addDays(referenceDate, 3)),
      time: "11:30",
      status: "pending",
      mode: "google_meet",
      location: "",
      meetingUrl: "",
      notes: "Primeiro contato pela agenda.",
      source: "Link público",
      createdAt: now,
      updatedAt: now,
    },
  ];
}
