import { addMonths, format } from "date-fns";
import type { OperationsState } from "./types";

const now = "2026-09-01T10:00:00.000Z";
const iso = (date: Date) => format(date, "yyyy-MM-dd");

export function createSeedOperations(
  referenceDate = new Date("2026-09-11T12:00:00.000Z"),
): OperationsState {
  const monthStart = new Date(
    referenceDate.getFullYear(),
    referenceDate.getMonth(),
    1,
  );
  return {
    services: [
      {
        id: "service-social",
        name: "Gestão de Comunicação",
        description:
          "Planejamento, produção e acompanhamento de comunicação digital.",
        category: "Comunicação",
        defaultPrice: 2000,
        billingType: "fixed",
        unit: "mês",
        defaultDurationDays: 30,
        fiscalCode: "",
        taxRate: 0,
        contractTemplateId: null,
        standardTasks: [
          "Planejamento editorial",
          "Produção de conteúdos",
          "Revisão com cliente",
          "Relatório mensal",
        ],
        recurrence: "monthly",
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "service-website",
        name: "Criação de Website",
        description:
          "Projeto completo de planejamento, design, desenvolvimento e publicação.",
        category: "Digital",
        defaultPrice: 6500,
        billingType: "fixed",
        unit: "projeto",
        defaultDurationDays: 45,
        fiscalCode: "",
        taxRate: 0,
        contractTemplateId: null,
        standardTasks: [
          "Briefing",
          "Wireframe",
          "Design",
          "Desenvolvimento",
          "Revisão",
          "Publicação",
        ],
        recurrence: "none",
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "service-consulting",
        name: "Consultoria estratégica",
        description: "Análise, recomendações e encontros de acompanhamento.",
        category: "Consultoria",
        defaultPrice: 350,
        billingType: "variable",
        unit: "hora",
        defaultDurationDays: 15,
        fiscalCode: "",
        taxRate: 0,
        contractTemplateId: null,
        standardTasks: [
          "Diagnóstico",
          "Plano de ação",
          "Reunião de acompanhamento",
        ],
        recurrence: "none",
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
    opportunities: [
      {
        id: "opp-anoreg",
        name: "ANOREG/TO",
        company: "ANOREG/TO",
        phone: "",
        email: "",
        serviceId: "service-social",
        source: "Indicação",
        estimatedValue: 2000,
        notes: "Renovação da comunicação institucional.",
        nextAction: "Enviar apresentação do escopo",
        nextActionDate: iso(addMonths(monthStart, 0)),
        status: "won",
        clientId: "anoreg",
        quoteId: "quote-anoreg",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "opp-new",
        name: "Novo projeto de site",
        company: "Empresa em prospecção",
        phone: "",
        email: "",
        serviceId: "service-website",
        source: "Site",
        estimatedValue: 6500,
        notes: "Solicitou proposta para novo site institucional.",
        nextAction: "Fazer reunião de descoberta",
        nextActionDate: iso(addMonths(monthStart, 0)),
        status: "quote_requested",
        clientId: null,
        quoteId: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
    quotes: [
      {
        id: "quote-anoreg",
        number: "ORC-2026-001",
        clientId: "anoreg",
        opportunityId: "opp-anoreg",
        items: [
          {
            id: "quote-item-anoreg",
            serviceId: "service-social",
            description: "Gestão de Comunicação — Setembro/2026",
            quantity: 1,
            unitPrice: 2000,
            discount: 0,
            addition: 0,
          },
        ],
        description: "Gestão de Comunicação para o período de setembro.",
        estimatedDeadline: "30 dias",
        validUntil: "2026-09-30",
        notes: "",
        terms: "Pagamento mensal conforme contrato.",
        paymentMethod: "Pix ou transferência",
        status: "approved",
        approvedAt: "2026-09-01T10:00:00.000Z",
        engagementId: "eng-anoreg-september",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "quote-draft",
        number: "ORC-2026-002",
        clientId: null,
        opportunityId: "opp-new",
        items: [
          {
            id: "quote-item-draft",
            serviceId: "service-website",
            description: "Criação de Website",
            quantity: 1,
            unitPrice: 6500,
            discount: 0,
            addition: 0,
          },
        ],
        description: "Website institucional responsivo.",
        estimatedDeadline: "45 dias",
        validUntil: "2026-09-25",
        notes: "",
        terms: "50% no início e 50% na entrega.",
        paymentMethod: "Pix",
        status: "draft",
        approvedAt: null,
        engagementId: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
    engagements: [
      {
        id: "eng-anoreg-september",
        name: "Gestão de Comunicação — Setembro/2026",
        clientId: "anoreg",
        serviceId: "service-social",
        responsible: "",
        status: "in_progress",
        description: "Execução mensal da gestão de comunicação institucional.",
        startDate: "2026-09-01",
        dueDate: "2026-09-30",
        value: 2000,
        quoteId: "quote-anoreg",
        contractId: null,
        recurrence: "monthly",
        cycleValue: 2000,
        createdAt: now,
        updatedAt: now,
      },
    ],
    cycles: [
      {
        id: "cycle-anoreg-september",
        engagementId: "eng-anoreg-september",
        label: "Setembro/2026",
        startDate: "2026-09-01",
        endDate: "2026-09-30",
        status: "open",
        createdAt: now,
      },
    ],
    deliverables: [
      {
        id: "deliverable-anoreg-1",
        engagementId: "eng-anoreg-september",
        title: "Calendário editorial de setembro",
        description: "Planejamento de temas e formatos para aprovação.",
        date: "2026-09-05",
        attachments: [],
        links: [],
        notes: "Aguardando retorno do cliente.",
        status: "waiting_approval",
        createdAt: now,
        updatedAt: now,
      },
    ],
    timeEntries: [
      {
        id: "time-anoreg-1",
        engagementId: "eng-anoreg-september",
        taskId: "seed-1",
        clientId: "anoreg",
        description: "Finalização das peças da campanha",
        date: "2026-09-08",
        minutes: 120,
        billable: true,
        createdAt: now,
        updatedAt: now,
      },
    ],
  };
}
