import { addMonths, format } from "date-fns";
import type { OperationsState } from "./types";

const now = "2026-09-01T10:00:00.000Z";
const iso = (date: Date) => format(date, "yyyy-MM-dd");
const quoteEvent = (
  kind: OperationsState["quotes"][number]["events"][number]["kind"],
  title: string,
  description: string,
) => ({
  id: `event-${kind}-${title.toLocaleLowerCase("pt-BR").replace(/[^a-z0-9]+/g, "-")}`,
  kind,
  title,
  description,
  actor: "Você",
  createdAt: now,
});

export function createSeedOperations(
  referenceDate = new Date("2026-09-11T12:00:00.000Z"),
): OperationsState {
  const monthStart = new Date(
    referenceDate.getFullYear(),
    referenceDate.getMonth(),
    1,
  );
  return {
    services: [
      {
        id: "service-social",
        name: "Gestão de Comunicação",
        description:
          "Planejamento, produção e acompanhamento de comunicação digital.",
        category: "Comunicação",
        defaultPrice: 2000,
        billingType: "fixed",
        unit: "mês",
        defaultDurationDays: 30,
        fiscalCode: "",
        taxRate: 0,
        contractTemplateId: null,
        standardTasks: [
          "Planejamento editorial",
          "Produção de conteúdos",
          "Revisão com cliente",
          "Relatório mensal",
        ],
        recurrence: "monthly",
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "service-website",
        name: "Criação de Website",
        description:
          "Projeto completo de planejamento, design, desenvolvimento e publicação.",
        category: "Digital",
        defaultPrice: 6500,
        billingType: "fixed",
        unit: "projeto",
        defaultDurationDays: 45,
        fiscalCode: "",
        taxRate: 0,
        contractTemplateId: null,
        standardTasks: [
          "Briefing",
          "Wireframe",
          "Design",
          "Desenvolvimento",
          "Revisão",
          "Publicação",
        ],
        recurrence: "none",
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "service-consulting",
        name: "Consultoria estratégica",
        description: "Análise, recomendações e encontros de acompanhamento.",
        category: "Consultoria",
        defaultPrice: 350,
        billingType: "variable",
        unit: "hora",
        defaultDurationDays: 15,
        fiscalCode: "",
        taxRate: 0,
        contractTemplateId: null,
        standardTasks: [
          "Diagnóstico",
          "Plano de ação",
          "Reunião de acompanhamento",
        ],
        recurrence: "none",
        archivedAt: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
    opportunities: [
      {
        id: "opp-anoreg",
        name: "ANOREG/TO",
        company: "ANOREG/TO",
        phone: "",
        email: "",
        serviceId: "service-social",
        source: "Indicação",
        estimatedValue: 2000,
        notes: "Renovação da comunicação institucional.",
        nextAction: "Enviar apresentação do escopo",
        nextActionDate: iso(addMonths(monthStart, 0)),
        status: "won",
        clientId: "anoreg",
        quoteId: "quote-anoreg",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "opp-new",
        name: "Novo projeto de site",
        company: "Empresa em prospecção",
        phone: "",
        email: "",
        serviceId: "service-website",
        source: "Site",
        estimatedValue: 6500,
        notes: "Solicitou proposta para novo site institucional.",
        nextAction: "Fazer reunião de descoberta",
        nextActionDate: iso(addMonths(monthStart, 0)),
        status: "quote_requested",
        clientId: null,
        quoteId: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
    quotes: [
      {
        id: "quote-anoreg",
        number: "ORC-2026-001",
        clientId: "anoreg",
        opportunityId: "opp-anoreg",
        items: [
          {
            id: "quote-item-anoreg",
            serviceId: "service-social",
            savedItemId: "service-social",
            name: "Gestão de Comunicação",
            description: "Gestão de Comunicação — Setembro/2026",
            quantity: 1,
            unit: "month",
            customUnit: "",
            unitPrice: 2000,
            discountType: "none",
            discountValue: 0,
            discount: 0,
            addition: 0,
            fiscalCode: "",
            taxRate: 0,
          },
        ],
        title: "Gestão de Comunicação — Setembro/2026",
        description: "Gestão de Comunicação para o período de setembro.",
        issueDate: "2026-09-01",
        estimatedDeadline: "30 dias",
        validUntil: "2026-09-30",
        responsible: "Eduardo Vieira",
        discountType: "none",
        discountValue: 0,
        taxType: "none",
        taxLabel: "",
        taxValue: 0,
        paymentCondition: "cash",
        downPaymentPercent: 0,
        installments: 1,
        firstDueDate: "2026-09-05",
        paymentDetails: "Pagamento mensal conforme contrato.",
        estimatedStartDate: "2026-09-01",
        estimatedEndDate: "2026-09-30",
        scope:
          "<ul><li>Planejamento editorial</li><li>Produção de conteúdos</li><li>Relatório mensal</li></ul>",
        exclusions:
          "<ul><li>Impulsionamento de mídia</li><li>Produção de fotos externas</li></ul>",
        notes: "",
        terms: "Pagamento mensal conforme contrato.",
        paymentMethod: "Pix ou transferência",
        status: "approved",
        version: 1,
        parentQuoteId: null,
        publicToken: "wkq_public_anoreg_2026_001",
        viewedAt: "2026-09-01T14:30:00.000Z",
        approvedAt: "2026-09-01T10:00:00.000Z",
        rejectedAt: null,
        rejectionReason: "",
        acceptedBy: "ANOREG/TO",
        engagementId: "eng-anoreg-september",
        chargeId: null,
        contractId: null,
        events: [
          quoteEvent(
            "created",
            "Orçamento criado",
            "Orçamento cadastrado na Weeki.",
          ),
          quoteEvent(
            "viewed",
            "Cliente visualizou",
            "A proposta foi aberta pelo cliente.",
          ),
          quoteEvent(
            "approved",
            "Orçamento aprovado",
            "Aceite comercial registrado.",
          ),
        ],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "quote-draft",
        number: "ORC-2026-002",
        clientId: null,
        opportunityId: "opp-new",
        items: [
          {
            id: "quote-item-draft",
            serviceId: "service-website",
            savedItemId: "service-website",
            name: "Criação de Website",
            description: "Criação de Website",
            quantity: 1,
            unit: "project",
            customUnit: "",
            unitPrice: 6500,
            discountType: "none",
            discountValue: 0,
            discount: 0,
            addition: 0,
            fiscalCode: "",
            taxRate: 0,
          },
        ],
        title: "Website institucional responsivo",
        description: "Website institucional responsivo.",
        issueDate: "2026-09-11",
        estimatedDeadline: "45 dias",
        validUntil: "2026-09-25",
        responsible: "Eduardo Vieira",
        discountType: "none",
        discountValue: 0,
        taxType: "none",
        taxLabel: "",
        taxValue: 0,
        paymentCondition: "down_payment",
        downPaymentPercent: 50,
        installments: 2,
        firstDueDate: "2026-09-18",
        paymentDetails: "50% no início e 50% na entrega.",
        estimatedStartDate: "",
        estimatedEndDate: "",
        scope:
          "<ul><li>Planejamento da estrutura</li><li>Design responsivo</li><li>Desenvolvimento e publicação</li></ul>",
        exclusions:
          "<ul><li>Hospedagem</li><li>Domínio</li><li>Produção de fotografias</li></ul>",
        notes: "",
        terms: "50% no início e 50% na entrega.",
        paymentMethod: "Pix",
        status: "draft",
        version: 1,
        parentQuoteId: null,
        publicToken: "wkq_public_website_2026_002",
        viewedAt: null,
        approvedAt: null,
        rejectedAt: null,
        rejectionReason: "",
        acceptedBy: "",
        engagementId: null,
        chargeId: null,
        contractId: null,
        events: [
          quoteEvent(
            "created",
            "Rascunho criado",
            "Orçamento preparado a partir do catálogo de itens.",
          ),
        ],
        createdAt: now,
        updatedAt: now,
      },
    ],
    quoteTemplates: [
      {
        id: "quote-template-website",
        name: "Website institucional",
        description: "Modelo com escopo base, entrada e entrega final.",
        items: [
          {
            id: "template-item-website",
            serviceId: "service-website",
            savedItemId: "service-website",
            name: "Criação de Website",
            description: "Planejamento, design, desenvolvimento e publicação.",
            quantity: 1,
            unit: "project",
            customUnit: "",
            unitPrice: 6500,
            discountType: "none",
            discountValue: 0,
            discount: 0,
            addition: 0,
            fiscalCode: "",
            taxRate: 0,
          },
        ],
        estimatedDeadline: "45 dias",
        scope:
          "<ul><li>Briefing e arquitetura das páginas</li><li>Design responsivo</li><li>Desenvolvimento e publicação</li></ul>",
        exclusions:
          "<ul><li>Hospedagem</li><li>Domínio</li><li>Produção de fotos e vídeos</li></ul>",
        notes: "",
        terms: "Proposta válida até a data informada no orçamento.",
        paymentMethod: "Pix ou transferência",
        paymentCondition: "down_payment",
        downPaymentPercent: 50,
        installments: 2,
        paymentDetails: "50% na aprovação e 50% na entrega final.",
        createdAt: now,
        updatedAt: now,
        archivedAt: null,
      },
    ],
    quoteSettings: {
      prefix: "ORC",
      defaultValidityDays: 15,
      defaultDeadlineDays: 30,
      defaultTerms:
        "Valores sujeitos à aprovação formal. Alterações de escopo poderão gerar novo orçamento.",
      defaultNotes: "",
      defaultPaymentTerms: "Pagamento conforme condições comerciais aprovadas.",
      showLogo: true,
      showDocument: true,
      showAddress: true,
      showPhone: true,
      showSignature: true,
      footerText: "Orçamento comercial gerado pela Weeki.",
      currency: "BRL",
      decimalPlaces: 2,
    },
    engagements: [
      {
        id: "eng-anoreg-september",
        name: "Gestão de Comunicação — Setembro/2026",
        clientId: "anoreg",
        serviceId: "service-social",
        responsible: "",
        status: "in_progress",
        description: "Execução mensal da gestão de comunicação institucional.",
        startDate: "2026-09-01",
        dueDate: "2026-09-30",
        value: 2000,
        quoteId: "quote-anoreg",
        contractId: null,
        recurrence: "monthly",
        cycleValue: 2000,
        createdAt: now,
        updatedAt: now,
      },
    ],
    cycles: [
      {
        id: "cycle-anoreg-september",
        engagementId: "eng-anoreg-september",
        label: "Setembro/2026",
        startDate: "2026-09-01",
        endDate: "2026-09-30",
        status: "open",
        createdAt: now,
      },
    ],
    deliverables: [
      {
        id: "deliverable-anoreg-1",
        engagementId: "eng-anoreg-september",
        title: "Calendário editorial de setembro",
        description: "Planejamento de temas e formatos para aprovação.",
        date: "2026-09-05",
        attachments: [],
        links: [],
        notes: "Aguardando retorno do cliente.",
        status: "waiting_approval",
        createdAt: now,
        updatedAt: now,
      },
    ],
    timeEntries: [
      {
        id: "time-anoreg-1",
        engagementId: "eng-anoreg-september",
        taskId: "seed-1",
        clientId: "anoreg",
        description: "Finalização das peças da campanha",
        date: "2026-09-08",
        minutes: 120,
        billable: true,
        createdAt: now,
        updatedAt: now,
      },
    ],
  };
}
