import type { Client } from "./types";

const createdAt = "2026-01-12T10:00:00.000Z";

const baseClient = {
  logoUrl: "",
  kind: "company" as const,
  contactRole: "Contato principal",
  notes: "",
  status: "active" as const,
  contractKind: "none" as const,
  nextDueDate: "",
  paymentStatus: "none" as const,
  files: [],
  links: [],
  createdAt,
  updatedAt: createdAt,
};

export const createSeedClients = (): Client[] => [
  {
    ...baseClient,
    id: "clinic-lumi",
    name: "Clínica Lumi",
    initials: "CL",
    color: "#14b8a6",
    document: "",
    contactName: "",
    contactRole: "",
    email: "",
    phone: "",
    website: "",
    address: "",
    notes: "Cadastro demonstrativo. Substitua pelos dados do seu cliente.",
    segment: "Saúde & Clínica",
    contractValue: 0,
    files: [
      { id: "lumi-file-1", name: "Proposta 2024.pdf", size: 2400000, type: "application/pdf", createdAt },
      { id: "lumi-file-2", name: "Manual Marca.pdf", size: 8100000, type: "application/pdf", createdAt },
      { id: "lumi-file-3", name: "Contrato.docx", size: 540000, type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", createdAt },
    ],
    links: [
      { id: "lumi-link-1", label: "Área compartilhada", url: "https://example.com/" },
    ],
  },
  {
    ...baseClient,
    id: "anoreg",
    name: "ANOREG/TO",
    initials: "AN",
    color: "#7657ff",
    document: "",
    contactName: "",
    email: "",
    phone: "",
    website: "",
    address: "",
    segment: "Institucional",
    contractValue: 0,
  },
  {
    ...baseClient,
    id: "krd",
    name: "KRD Equipamentos",
    initials: "KR",
    color: "#2479db",
    document: "",
    contactName: "",
    email: "",
    phone: "",
    website: "",
    address: "",
    segment: "Indústria",
    contractValue: 0,
  },
  {
    ...baseClient,
    id: "weeki",
    name: "Weeki",
    initials: "WK",
    color: "#d8438e",
    document: "",
    contactName: "",
    email: "",
    phone: "",
    website: "",
    address: "",
    segment: "Produto digital",
    contractValue: 0,
    contractKind: "none",
    paymentStatus: "none",
  },
  {
    ...baseClient,
    id: "viajanatty",
    name: "ViajaNatty",
    initials: "VI",
    color: "#8b5cf6",
    document: "",
    contactName: "",
    email: "",
    phone: "",
    website: "",
    address: "",
    status: "negotiating",
    segment: "Turismo",
    contractValue: 0,
    contractKind: "none",
    paymentStatus: "none",
  },
  {
    ...baseClient,
    id: "casa-verde",
    name: "Casa Verde Arquitetura",
    initials: "CA",
    color: "#ec4899",
    document: "",
    contactName: "",
    email: "",
    phone: "",
    website: "",
    address: "",
    status: "inactive",
    segment: "Arquitetura",
    contractValue: 0,
    contractKind: "none",
    paymentStatus: "none",
  },
];
